name: MnemonicSwift
options:
  bundleIdPrefix: co.electriccoin
settings:
  LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks @loader_path/../Frameworks $(PROJECT_DIR)/Carthage/Build/iOS"
targets:
  MnemonicSwift:
    type: framework
    platform: [iOS, macOS]
    deploymentTarget:
      iOS: 13.1
    sources: [MnemonicSwift]
    scheme:
      testTargets:
        - MnemonicSwiftTests_${platform}
      gatherCoverageData: true
    postCompileScripts:
      - script: swiftlint autocorrect --config .swiftlint.yml
        name: SwiftLint

  MnemonicSwiftTests:
    type: bundle.unit-test
    platform: [iOS, macOS]
    sources: [Tests]
    dependencies:
      - target: MnemonicSwift_${platform}
